# Selim Tanriverdi and William Kelley
# CS 3013 C02 2016

runCommand: runCommand.c commandInfo.c commandInfo.h
	gcc -w -o runCommand runCommand.c commandInfo.c
	#./runCommand

clean:
	rm -f *.o out.txt runCommand